package Day14;

import java.util.Scanner;

public class ExceptionDemo {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		/*System.out.println("Program is started");
		System.out.println("Program is in progress");
		
		//example
		Scanner sc = new Scanner(System.in);
		System.out.println("Enter a number");
		
		int num=sc.nextInt();
		
		System.out.println(100/num);
		
		System.out.println("Program is completed");
		System.out.println("program is exited");*/
		

		
		//example
		
		/*int a[]= new int [5];
		
		Scanner sc = new Scanner (System.in);
		
		System.out.println("Enter a number");
		int num =sc.nextInt();
		
		System.out.println("Enter position(0-4):");
		int pos =sc.nextInt();
		
		a[pos]=num;  //Array index out off bounds exception
		
		System.out.println(a[pos]);*/
		
		//example3
		
		String s ="1234";
		int num=Integer.parseInt(s);
		System.out.println(num);
		System.out.println("program is completed");
		
		System.out.println("program is exited");
		
		
		
	}

}
